baseURL = "https://domicmeia.github.io/"
languageCode = "en-us"
title = "Domicmeia"
theme = "github-style-plus"
googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "domicmeia"
  description = "Any description?"
  github = "domicmeia"
  enableGithubFollowers = true 
  linkedin = "kimdomic"
  email = "dhdlqks55@gmail.com"
  lastmod = true
  userStatusEmoji = "😉"
  favicon = "/images/avatar.jpeg"
  avatar = "/images/avatar.jpeg"
  location = "Seoul"
  enableGitalk = false
  rss = true
  enableLocalSearch = true
  sponsorLink = "Your external sponsor link; For me, I use buymeacoffee link"
  gtmId = "your gtm id"
    
  [params.gitalk]
    accessToken = "Your Github access token" 
    repo = "domicmeia.github.io"
    owner = "domicmeia" 
    admin = "domicmeia" 
    id = "location.pathname" 
    labels = "gitalk" 
    perPage = 15 
    pagerDirection = "last" 
    createIssueManually = true 
    distractionFreeMode = false 
    proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token" 

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]